upstream backend {
    server backend:8000; # в этой группе один сервер: контейнер backend на порту 8000
}

upstream frontend {
    server frontend:8000; # в этой группе один сервер: контейнер frontend на порту 8000
}

server {
    listen 80; # Принимает все входящие запросы на порт основного сервера 80

    client_max_body_size 20M;

    location /api/ { # маршрутизация API запросов(перенаправляет запросы начинающиеся с /api/ на бэкэнд)
        proxy_pass http://backend; # Nginx сам найдёт контейнер backend:8000
        proxy_set_header Host $http_host; # Передаёт оригинальный Host заголовок от клиента к бэкенду(иначе внутреннее имя контейнера)
        proxy_set_header X-Real-IP $remote_addr; #Передаёт реальный IP-адрес клиента бэкенду.(без этого ip контейнера nginx)
    }

    location /admin/ { # Аналогично /api/ перенаправляет запросы в /admin/ на бэкенд
        proxy_pass http://backend;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /static/ { # Перехватывает запросы к /static/...
        proxy_pass http://frontend;  # ← Проксирование на frontend
        proxy_set_header Host $http_host;
    }

    location /media/ {  # Аналогично /static/ отдаёт медиа-файлы (картинки котиков) напрямую из volume media
        alias /media/;
    }

    location / { # всё остальное (фронтенд)
        proxy_pass http://frontend;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}